M48
; DRILL file {KiCad 9.0.6} date 2026-06-18T17:02:09+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-18T17:02:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X81.0Y-125.4
X81.6Y-36.8
X218.0Y-36.6
X218.0Y-124.4
M30
